// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class UserDb
{
    public int UserId { get; set; }

    public int UserTypeId { get; set; }

    public string UserName { get; set; } = null!;

    public string UserSurname { get; set; } = null!;

    public int? TelegramId { get; set; }

    public string Email { get; set; } = null!;

    public string Phone { get; set; } = null!;

    public int UserStatusId { get; set; }

    public string PasswordHash { get; set; } = null!;

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedUserId { get; set; }

    public DateTime DateOfBirth { get; set; }

    public virtual ICollection<OrderDb> OrderDbs { get; set; } = new List<OrderDb>();

    public virtual ICollection<Qeue> Qeues { get; set; } = new List<Qeue>();
}