// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class OrderDbConfiguration : IEntityTypeConfiguration<OrderDb>
    {
        public void Configure(EntityTypeBuilder<OrderDb> entity)
        {
            entity.HasKey(e => e.OrderId).HasName("order_db_pkey");

            entity.ToTable("order_db", "orders");

            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.EndDateTime).HasColumnName("end_date_time");
            entity.Property(e => e.IsPriority)
                .HasDefaultValue(false)
                .HasColumnName("is_priority");
            entity.Property(e => e.OrderStatusId).HasColumnName("order_status_id");
            entity.Property(e => e.ReservationId).HasColumnName("reservation_id");
            entity.Property(e => e.StartDateTime).HasColumnName("start_date_time");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.WorkShiftId).HasColumnName("work_shift_id");

            entity.HasOne(d => d.Reservation).WithMany(p => p.OrderDbs)
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("order_db_reservation_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.OrderDbs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("order_db_user_id_fkey");

            entity.HasOne(d => d.WorkShift).WithMany(p => p.OrderDbs)
                .HasForeignKey(d => d.WorkShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("order_db_work_shift_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderDb> entity);
    }
}
