// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class ReservationTableConfiguration : IEntityTypeConfiguration<ReservationTable>
    {
        public void Configure(EntityTypeBuilder<ReservationTable> entity)
        {
            entity
                .HasNoKey()
                .ToTable("reservation_table", "reservations");

            entity.Property(e => e.ReservationId).HasColumnName("reservation_id");
            entity.Property(e => e.TableId).HasColumnName("table_id");

            entity.HasOne(d => d.Reservation).WithMany()
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("reservation_table_reservation_id_fkey");

            entity.HasOne(d => d.Table).WithMany()
                .HasForeignKey(d => d.TableId)
                .HasConstraintName("reservation_table_table_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ReservationTable> entity);
    }
}
