// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class ReservationConfiguration : IEntityTypeConfiguration<Reservation>
    {
        public void Configure(EntityTypeBuilder<Reservation> entity)
        {
            entity.HasKey(e => e.ReservationId).HasName("reservation_pkey");

            entity.ToTable("reservation", "reservations");

            entity.Property(e => e.ReservationId).HasColumnName("reservation_id");
            entity.Property(e => e.CreateDateTime).HasColumnName("create_date_time");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.OriginTypeId).HasColumnName("origin_type_id");
            entity.Property(e => e.PersonQuantity).HasColumnName("person_quantity");
            entity.Property(e => e.ReservationStatusId).HasColumnName("reservation_status_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Reservation> entity);
    }
}
