// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class TableDbConfiguration : IEntityTypeConfiguration<TableDb>
    {
        public void Configure(EntityTypeBuilder<TableDb> entity)
        {
            entity.HasKey(e => e.TableId).HasName("table_db_pkey");

            entity.ToTable("table_db", "tables");

            entity.HasIndex(e => e.TableNumber, "table_db_table_number_key").IsUnique();

            entity.Property(e => e.TableId).HasColumnName("table_id");
            entity.Property(e => e.Comment)
                .HasMaxLength(256)
                .HasColumnName("comment");
            entity.Property(e => e.MaxCapacity).HasColumnName("max_capacity");
            entity.Property(e => e.TableNumber).HasColumnName("table_number");
            entity.Property(e => e.TableStatusId).HasColumnName("table_status_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TableDb> entity);
    }
}
