// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class UserDbConfiguration : IEntityTypeConfiguration<UserDb>
    {
        public void Configure(EntityTypeBuilder<UserDb> entity)
        {
            entity.HasKey(e => e.UserId).HasName("user_db_pkey");

            entity.ToTable("user_db", "users");

            entity.HasIndex(e => e.Email, "user_db_email_key").IsUnique();

            entity.HasIndex(e => e.Phone, "user_db_phone_key").IsUnique();

            entity.HasIndex(e => e.TelegramId, "user_db_telegram_id_key").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.Email)
                .HasMaxLength(60)
                .HasColumnName("email");
            entity.Property(e => e.ModifiedDate).HasColumnName("modified_date");
            entity.Property(e => e.ModifiedUserId).HasColumnName("modified_user_id");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(128)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(60)
                .HasColumnName("phone");
            entity.Property(e => e.TelegramId).HasColumnName("telegram_id");
            entity.Property(e => e.UserName)
                .HasMaxLength(30)
                .HasColumnName("user_name");
            entity.Property(e => e.UserStatusId).HasColumnName("user_status_id");
            entity.Property(e => e.UserSurname)
                .HasMaxLength(60)
                .HasColumnName("user_surname");
            entity.Property(e => e.UserTypeId).HasColumnName("user_type_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserDb> entity);
    }
}
