// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class WorkShiftConfiguration : IEntityTypeConfiguration<WorkShift>
    {
        public void Configure(EntityTypeBuilder<WorkShift> entity)
        {
            entity.HasKey(e => e.WorkShiftId).HasName("work_shift_pkey");

            entity.ToTable("work_shift", "work_shifts");

            entity.Property(e => e.WorkShiftId).HasColumnName("work_shift_id");
            entity.Property(e => e.EndDateTime).HasColumnName("end_date_time");
            entity.Property(e => e.StartDateTime).HasColumnName("start_date_time");
            entity.Property(e => e.WorkShiftStatusId).HasColumnName("work_shift_status_id");
            entity.Property(e => e.WorkShiftUserTypeId).HasColumnName("work_shift_user_type_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkShift> entity);
    }
}
