// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PostGreContext.Context;
using PostGreContext.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace PostGreContext.Context.Configurations
{
    public partial class WorkShiftUserConfiguration : IEntityTypeConfiguration<WorkShiftUser>
    {
        public void Configure(EntityTypeBuilder<WorkShiftUser> entity)
        {
            entity
                .HasNoKey()
                .ToTable("work_shift_user", "work_shifts");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.WorkShiftId).HasColumnName("work_shift_id");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("work_shift_user_user_id_fkey");

            entity.HasOne(d => d.WorkShift).WithMany()
                .HasForeignKey(d => d.WorkShiftId)
                .HasConstraintName("work_shift_user_work_shift_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkShiftUser> entity);
    }
}
