// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class Reservation
{
    public int ReservationId { get; set; }

    public int? OriginTypeId { get; set; }

    public int ReservationStatusId { get; set; }

    public TimeSpan Duration { get; set; }

    public DateTime CreateDateTime { get; set; }

    public int PersonQuantity { get; set; }

    public virtual ICollection<OrderDb> OrderDbs { get; set; } = new List<OrderDb>();
}