// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class ReservationTable
{
    public int? ReservationId { get; set; }

    public int? TableId { get; set; }

    public virtual Reservation? Reservation { get; set; }

    public virtual TableDb? Table { get; set; }
}