// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class Qeue
{
    public int QeueId { get; set; }

    public int WorkShiftId { get; set; }

    public int UserId { get; set; }

    public int QeueStatusId { get; set; }

    public int OrderSequence { get; set; }

    public int? PriorityOrderSequence { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public virtual UserDb User { get; set; } = null!;

    public virtual WorkShift WorkShift { get; set; } = null!;
}