// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class TableDb
{
    public int TableId { get; set; }

    public int TableNumber { get; set; }

    public int TableStatusId { get; set; }

    public int MaxCapacity { get; set; }

    public string? Comment { get; set; }

    public virtual ICollection<OrderTable> OrderTables { get; set; } = new List<OrderTable>();
}