// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class WorkShiftUser
{
    public int? WorkShiftId { get; set; }

    public int? UserId { get; set; }

    public virtual UserDb? User { get; set; }

    public virtual WorkShift? WorkShift { get; set; }
}