// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostGreContext.Models;

public partial class WorkShift
{
    public int WorkShiftId { get; set; }

    public int WorkShiftUserTypeId { get; set; }

    public int WorkShiftStatusId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public virtual ICollection<OrderDb> OrderDbs { get; set; } = new List<OrderDb>();

    public virtual ICollection<Qeue> Qeues { get; set; } = new List<Qeue>();
}